# 基础镜像
FROM nacos/nacos-server
# author
MAINTAINER ruoyi

# 设置 JVM UTF-8 编码参数（解决中文乱码问题）
ENV JAVA_OPT="-Dfile.encoding=UTF-8 -Dclient.encoding.override=UTF-8"

# 复制 conf 文件到路径
COPY ./conf/application.properties /flowmind/nacos/conf/application.properties
