# 基础镜像
FROM eclipse-temurin:17-jre
# author

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制 jar 文件到路径
COPY ./jar/ruoyi-modules-flowable.jar /home/ruoyi/ruoyi-modules-flowable.jar
# 启动 Flowable 流程服务
ENTRYPOINT ["java","-jar","ruoyi-modules-flowable.jar"]
